### ISSUE TITLE
Contribution Youtube clone

### ISSUE THREAD

**Issue by Rafsdias** [GorvGoyl/Clone-Wars#11]
clone name: Youtube UI Clone
code repo link: https://github.com/Rafsdias/youtube-UI-clone
demo link: https://rafaeldias-youtube.surge.sh/
tech stack used: HTML + CSS (SASS)

**Comment by GorvGoyl** [comment]
hey there, thanks for submitting request. However, based on the feedback from community, I'm not taking any new 'UI only' clones. Thanks again.
