### ISSUE TITLE
Hide Demo Link and Repo Link behind short words to improve table view

### ISSUE THREAD

**Issue by mani-barathi** [GorvGoyl/Clone-Wars#118]
## Problem
The tech stack, stars are hard to see in the README table

## Solution
We can hide the full links for Demo and Repo behind short words (like Live Link and GitHub) so that the table will get more space, and it also looks clean

### Before
| Clone/Alt of                   | Demo                                                                                                                   | Repo                                                                                                                   | Tech stack                                             | Repo Stars                                                                                                                                                                                     |
| ------------------------------ | ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1Password / LastPass           | https://bitwarden.com/                                                                                                 | https://github.com/bitwarden/mobile                                                                                    | C#, Xamarin                                            | ![GitHub Repo stars](https://img.shields.io/github/stars/bitwarden/mobile)                                                                                                                     |
| 2048                           | https://gh.artemchep.com/2048/#/                                                                                       | https://github.com/AChep/2048                                                                                          | Dart, Flutter                                          | ![GitHub Repo stars](https://img.shields.io/github/stars/AChep/2048)                                                                                                                           |

### After
| Clone/Alt of                   | Demo                                                                                                                   | Repo                                                                                                                   | Tech stack                                             | Repo Stars                                                                                                                                                                                     |
| ------------------------------ | ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1Password / LastPass           |[Live Link](https://bitwarden.com/)                                                                                                | [GitHub](https://github.com/bitwarden/mobile)                                                                                   | C#, Xamarin                                            | ![GitHub Repo stars](https://img.shields.io/github/stars/bitwarden/mobile)                                                                                                                     |
| 2048                           | [Live Link](https://gh.artemchep.com/2048/#/)                                                                                       | [GitHub ](https://github.com/AChep/2048)                                                                                      | Dart, Flutter                                          | ![GitHub Repo stars](https://img.shields.io/github/stars/AChep/2048)                                                                                                                           |

**Comment by mani-barathi** [comment]
@GorvGoyl If you like it, assign this Issue to me. I'll make the changes and make a PR.

**Comment by GorvGoyl** [comment]
that's goin to be lot of manual work :D , I'd be grateful if someone could chip in and improve this repo. Thanks @mani-barathi , you can send me a PR and I'll merge.

**Comment by mani-barathi** [comment]
> that's going to be lot of manual work :D , I'd be grateful if someone could chip in and improve this repo. Thanks @mani-barathi , you can send me a PR and I'll merge.

@GorvGoyl 
 It wasn't hard, because I use **Vim** for editing 😎
