### ISSUE TITLE
markdown link in README is broken

### ISSUE THREAD

**Issue by mani-barathi** [GorvGoyl/Clone-Wars#126]
[**mardown.site**](https://markdown.site) link in contribution section of readme is broken.
I checked out for alternate online markdown editors and [**dillinger.io**](https://dillinger.io/) was really good

@GorvGoyl If you are ok with dillinger.io, I'll fix it with a quick PR

**Comment by mani-barathi** [comment]
@GorvGoyl ??

**Comment by GorvGoyl** [comment]
thanks for the ping. totally missed it. yes sure, please ho ahead and send me the PR

**Comment by mani-barathi** [comment]
@GorvGoyl can you check the PR
