### ISSUE TITLE
[Feature Requested] Would be possible to incorporate a chat community related to this repo? 

### ISSUE THREAD

**Issue by denik1981** [GorvGoyl/Clone-Wars#129]
Honestly I haven't found any community related to proyect-making challenges. Most of them are organized by technology or general/random concepts but none like #airbnb-clone, #amazon-clone, etc. Would it be possible to create a Clone-Wars Slack, discord or whatever server (I personally prefer a chat server) that suit all of us well for this kind of repo to make people join togetther and work as a collective group of self-taught devs?

 
Thanks for setting up this repo. It is indedd very helpful.

**Comment by Shan2017** [comment]
> Honestly I haven't found any community related to proyect-making challenges. Most of them are organized by technology or general/random concepts but none like #airbnb-clone, #amazon-clone, etc. Would it be possible to create a Clone-Wars Slack, discord or whatever server (I personally prefer a chat server) that suit all of us well for this kind of repo to make people join togetther and work as a collective group of self-taught devs?
> 
>  
> Thanks for setting up this repo. It is indedd very helpful.
> 
> 
>   

thanks

**Comment by Shan2017** [comment]
locasion

**Comment by denik1981** [comment]
I will close this issue as I think is no longer relevant.
