### ISSUE TITLE
Apple Music

### ISSUE THREAD

**Issue by oriravid** [GorvGoyl/Clone-Wars#13]
Hi folks, what an excellent resource I stumbled upon!

I noticed there's no clone for Apple Music here, so I figured I'd submit mine into the mix. Thanks :)

Clone Name: Apple Music
Repo Link: https://github.com/oriravid/Appo-Music
Demo Link: https://appo-music.herokuapp.com/
Tech Stack: React, Redux, Ruby on Rails, PostgreSQL

**Comment by GorvGoyl** [comment]
just wow!
done.
