### ISSUE TITLE
Mozilla Vpn

### ISSUE THREAD

**Issue by nnivxix** [GorvGoyl/Clone-Wars#14]
Cloned Landing Page Mozilla using *Webpack Bootstrap*
Link [Demo](mozilla-vpn.web.app) link [repo](https://github.com/nnivxix/mozila-vpn)

**Comment by ryanmcdonough** [comment]
Demo landing page is throwing a 404.

**Comment by GorvGoyl** [comment]
hey there, thanks for submitting request. However, based on the feedback from community, I'm not taking any new 'UI only' clones. Thanks again.
