### ISSUE TITLE
License metadata

### ISSUE THREAD

**Issue by md5** [GorvGoyl/Clone-Wars#17]
Great resource Gourav! Have you considered adding a "License" column to your listing? I imagine that many users would find having that information at a glance helpful.

**Comment by GorvGoyl** [comment]
hey thanks for suggestion. however, I won't be able to track if repo author changes the license later. I'm just maintaining an index to repo links, if someone's interested he can navigate to the repo to see the additional details like license, build steps etc.

**Comment by md5** [comment]
Sounds good!
