### ISSUE TITLE
Contribution: Trello clone

### ISSUE THREAD

**Issue by arturmolenda** [GorvGoyl/Clone-Wars#2]
clone name: Trello
repo: https://github.com/arturmolenda/project-manager
demo: https://project-manager1.herokuapp.com/
tech stack: React, Redux, Node, Express, Socket.io, MongoDB

**Comment by GorvGoyl** [comment]
done, thanks

**Comment by arturmolenda** [comment]
Hey, this is first time my project got featured anywhere and it means a lot
to me, I just wanted to thank you for it. Thanks!
