### ISSUE TITLE
added to privacytoolslist.com

### ISSUE THREAD

**Issue by privacytoolslist** [GorvGoyl/Clone-Wars#27]
Hello, Nice list! I added it to privacytoolslist.com ([other lists section](https://privacytoolslist.com/#alternative-privacy-lists)) with link to your site. If it's possible please add backlink somewhere. thanks

p.s. my other 5 cents website UI is not intuitive. At the beginning, I did not understand where the whole list was on the site and only then I saw that main sections has scrollbar.

**Comment by GorvGoyl** [comment]
Thank you for the mention 🙌. I'll surely see what I can do from my side. And, thank you for the valuable feedback on the website UI design, I've fixed it for the desktop users and trying to make it better for mobile layout.
Closing this as a non-issue but please feel free to discuss anything.
