### ISSUE TITLE
Disney+ link not working

### ISSUE THREAD

**Issue by Joshii01** [GorvGoyl/Clone-Wars#28]
Hello there! it seems to be that when i click on the disney+ link it takes me to an image instead, here is the link: https://github.com/calebnance/expo-disneyplus/blob/master/.gh-assets/screenshare-4.png?raw=true

**Comment by GorvGoyl** [comment]
unfortunately the repo author didn't provide any working demo link, so, I put these screenshot to get some visual idea. You could try filing an issue for that repository for demo link.
