### ISSUE TITLE
6 free full-length courses + codebases for building these clones

### ISSUE THREAD

**Issue by QuincyLarson** [GorvGoyl/Clone-Wars#55]
Hi @GorvGoyl this is an awesome list of projects, and you've been really thoughtful about how you share these codebases / demos.

Here are 6 courses focused on building out these clones of popular websites / apps that I think could be a fit, but these are courses (rather than just demos):

- [Whatsapp clone using Android](https://www.freecodecamp.org/news/native-android-app-tutorial-whatsapp-clone/)
- [Instagram clone using React Native + Firebase + Redux + Expo](https://www.freecodecamp.org/news/build-an-instagram-clone-with-react-native-firebase-firestore-redux-and-expo/)
- [YouTube clone using PHP yii2](https://www.freecodecamp.org/news/learn-how-to-use-the-yii2-php-framework-to-create-a-youtube-clone/)
- [Twitter clone using Vue](https://www.freecodecamp.org/news/create-a-cross-platform-twitter-clone-with-vue-js/)
- [Todoist clone using React + Firebase](https://www.freecodecamp.org/news/react-firebase-todoist-clone/)
- [Moodle clone using Django](https://www.freecodecamp.org/news/django-rest-framework-react-tutorial/)

Since these are links to multi-hour code-along-at-home tutorials, I didn't want to open a PR without your further input. Also, I'm proposing we link to the courses instead of the demos, since the courses are designed for beginners to code along and build out these apps themselves.

These courses and their codebases are freely available on the freeCodeCamp community YouTube channel.

What are your thoughts on this?

**Comment by GorvGoyl** [comment]
Huge fan of your work Quincy! You purposed a really good idea and it seems like a natural fit for this collection. How should we go about adding tutorials? I could think of 2 ways

1. Add extra column for tutorial link. Useful if many of the clones have a tutorial. This project has around 120 clones/alternatives.

2. If we have have limited number of tutorials available we could add tutorial link to the column ("Demo") and rename it to something like "Demo & Tutorial".

Open to suggestions.

> link to the courses instead of the demos

I'd still suggest to keep a demo link, as someone would expect to see what it'd look like (end result) before she/he invest time in following a tutorial.

**Comment by Arun-kc** [comment]
Hi @GorvGoyl, I would suggest going with your second suggestion as it would be more helpful to go through tutorials along with the demo.

**Comment by devagarwal2503** [comment]
Hey @GorvGoyl,
I think it is the best way is to go with your 1st idea, as many people want to experience what they are making.
Doing this will help the Newbies and content creates.

**Comment by QuincyLarson** [comment]
Hi @GorvGoyl, thank you for your kind words. I'm excited to hear you're already familiar with our open source community.

And yes, if we wanted to have live demos of these (some of which involve more elaborate back end setups) we would need to go in and host them somewhere – perhaps on Repl.it or Heroku. This would be a bit of extra work. I myself haven't worked with Yii2, and I'm not sure how we'd demo the Android app in a browser.

The courses and their codebases, however, are ready to go, and could be included in your list without a lot of extra work.

Either of the approaches you, @Arun-kc and @devagarwal2503 proposed are fine with me. Yet another approach might be to create a second table specifically for courses. I know a quite a few developer/teachers on YouTube who have free courses on building clones of popular websites, and I could reach out to them and encourage them to open PRs as well.

**Comment by Arun-kc** [comment]
What @devagarwal2503 said is right as what everyone looking for is a hands-on experience on these projects. But what @GorvGoyl proposed at first is to add an extra column to the already existing table. So it would feel empty if we are not able to fill up that column with tutorial/course links as there are over 100+ rows in this table. 

I like the idea of @QuincyLarson, creating a new table specifically for courses. It would be really good if you are able to fill the tables with free courses and tutorials.  If that's possible I would suggest going with what Quincy proposed.

I'm new to all these open-source contributions. So excuse me if I used a lot of pings.

**Comment by GorvGoyl** [comment]
Great feedback guys.

> if we wanted to have live demos of these we would need to go in and host them somewhere

Agree with your point. Would it be possible to also show some kind of mockup, video, or GIF as demo. I think this will encourage students more as they will be able to see the expected end-result before taking the course. Currently, some of the demo links in `clone-wars` are just [video (Amazon clone)](https://www.youtube.com/watch?v=MSctN0MOdt0), [Screenshots (disneyplus clone)](https://raw.githubusercontent.com/calebnance/expo-disneyplus/master/.gh-assets/screenshare-4.png). We can always leave the demo column empty if project has none.

> second table specifically for courses

Agree, I think this is a better approach and will help students easily find out the clones with tutorials. I'm thinking of adding below columns to that table. What all you think?

1. Clone of
2. Demo (_can provide url/screenshot/gif/video or leave empty_)
3. Course/Tutorial link
4. Repo links (_not sure about this column as course/tutorial already provide all supported links. if some link gets changed then author has to do modify at 2 places. need more inputs from you guys_)

**Comment by devagarwal2503** [comment]
> Great feedback guys.
> 
> > if we wanted to have live demos of these we would need to go in and host them somewhere
> 
> Agree with your point. Would it be possible to also show some kind of mockup, video, or GIF as demo. I think this will encourage students more as they will be able to see the expected end-result before taking the course. Currently, some of the demo links in `clone-wars` are just [video (Amazon clone)](https://www.youtube.com/watch?v=MSctN0MOdt0), [Screenshots (disneyplus clone)](https://raw.githubusercontent.com/calebnance/expo-disneyplus/master/.gh-assets/screenshare-4.png). We can always leave the demo column empty if project has none.
> 
> > second table specifically for courses
> 
> Agree, I think this is a better approach and will help students easily find out the clones with tutorials. I'm thinking of adding below columns to that table. What all you think?
> 
> 1. Clone of
> 2. Demo (_can provide url/screenshot/gif/video or leave empty_)
> 3. Course/Tutorial link
> 4. Repo links (_not sure about this column as course/tutorial already provide all supported links. if some link gets changed then author has to do modify at 2 places. need more inputs from you guys_)

Definitely, this approach can work.
there are so many Youtube tutorials that can be added to the table.

**Comment by devagarwal2503** [comment]
There are many Youtube tutorials from freecodecamp.org and many other YouTubers. But the newcomers to CS cannot find them, If we can provide all the important material in one place that will help them to work on their project more effectively.

**Comment by dimi-fn** [comment]
Inspiring by this issue, I made a PR in order to 1) format the main table 2) introduce a new section and table suggested by @QuincyLarson which also seems to be agreed by @GorvGoyl. The details of my suggestions can be found [at the PR](https://github.com/GorvGoyl/Clone-Wars/pull/100).

**Comment by GorvGoyl** [comment]
Hey @QuincyLarson , now we have 2 tables (thanks to @dimi-fn  for adding clones with tutorials). You can see that table here [clones-with-tutorials](https://github.com/GorvGoyl/Clone-Wars#clones-with-tutorials). What do you think about it.   
 Could we encourage other devs/youtubers who have clone tutorials to contribute.

**Comment by QuincyLarson** [comment]
@GorvGoyl Thanks for your patience – this thread got buried in my GitHub notifications. 😅 

@dimi-fn This PR looks fantastic. This is everything I imagined and more. 

I am part of a big developer YouTube creator discord server, and I'm going to tell them to check out this project and add some of their own app cloning tutorials as well.

If it's OK with you all, we will continue to swing by and open pull requests with new app clone courses from time to time as we publish them. And I will close this issue thread for now, and you all can reopen it if you want to discuss this further.

Thank you again for creating and maintaining this awesome project.
