### ISSUE TITLE
Serious open-source alternatives

### ISSUE THREAD

**Issue by CrazyPython** [GorvGoyl/Clone-Wars#66]
Discord - Matrix

YouTube - PeerTube

YouTube - LBRY

Substack - WordPress

**Comment by 6r1d** [comment]
Issue seems to be a bit stale and I guess I'll bump it.

* LBRY is not a very direct clone of YouTube, but is a good alternative service.
* PeerTube is nice, too.
* Matrix doesn't look like a direct clone of Discord interface-wise, but is that a requirement?

Then again, I haven't read docs on CloneWars, just wonder if those services fit or not.

**Comment by CrazyPython** [comment]
Another:

Substack - Ghost. Two platforms are very similar, both minimalist

**Comment by GorvGoyl** [comment]
I'd be grateful if someone could send me PR of these clones.. I'd be happy to review and merge.

**Comment by TurMitaev** [comment]
> Issue seems to be a bit stale and I guess I'll bump it.
> 
> * LBRY is not a very direct clone of YouTube, but is a good alternative service.
> * PeerTube is nice, too.
> * Matrix doesn't look like a direct clone of Discord interface-wise, but is that a requirement?
> 
> Then again, I haven't read docs on CloneWars, just wonder if those services fit or not.
