### ISSUE TITLE
Facebook-wall clone

### ISSUE THREAD

**Issue by m1k1o** [GorvGoyl/Clone-Wars#72]
This is just a simple facebook wall clone. Can be self-hosted as a blog.

Repo:
https://github.com/m1k1o/blog/

Demo:
https://blog.m1k1o.net/

Stack:
PHP

Not sure if it is "enough" clone, since it is only the wall.

**Comment by GorvGoyl** [comment]
I'm afraid, this won't cut the list. Sorry.
