### ISSUE TITLE
Stackoverflow clone 

### ISSUE THREAD

**Issue by killvung** [GorvGoyl/Clone-Wars#77]
clone name: stack-underflow-mern-gql
code repo link: https://github.com/amand33p/stack-underflow-mern-gql
demo link: https://stackunderflow.netlify.app
tech stack: MERN (MongoDB, Express, React, NodeJS)

**Comment by devagarwal2503** [comment]
Is this repo has to be added to the list?

**Comment by killvung** [comment]
yes. It looks legit awesome!!

**Comment by amand33p** [comment]
@killvung Go ahead! I like the Clone Wars initiative.

**Comment by GorvGoyl** [comment]
merged.
